/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <android/log.h>
#include <stddef.h>
#include "log.h"


#ifndef _Included_com_uowee_android_screen_live_rtmp_RtmpClient
#define _Included_com_uowee_android_screen_live_rtmp_RtmpClient
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jlong JNICALL Java_com_uowee_android_screen_live_rtmp_RtmpClient_open
  (JNIEnv *, jclass, jstring, jboolean);


JNIEXPORT jint JNICALL Java_com_uowee_android_screen_live_rtmp_RtmpClient_read
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint);


JNIEXPORT jint JNICALL Java_com_uowee_android_screen_live_rtmp_RtmpClient_write
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint, jint);


JNIEXPORT jint JNICALL Java_com_uowee_android_screen_live_rtmp_RtmpClient_close
 (JNIEnv * env,jlong , jobject );


JNIEXPORT jstring JNICALL Java_com_uowee_android_screen_live_rtmp_RtmpClient_getIpAddr
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
